[colors.primary]
background = '#0e1416'
foreground = '#dee3e5'

[colors.cursor]
text = '#dee3e5'
cursor = '#bfc8ca'

[colors.vi_mode_cursor]
text = '#0e1416'
cursor = '#83d2e3'

[colors.search.matches]
foreground = '#3f484a'
background = '#bcc5eb'

[colors.search.focused_match]
foreground = '#3f484a'
background = '#83d2e3'

[colors.footer_bar]
foreground = '#3f484a'
background = '#dee3e5'

[colors.hints.start]
foreground = '#3f484a'
background = '#b1cbd1'

[colors.hints.end]
foreground = '#3f484a'
background = '#b1cbd1'

[colors.selection]
text = '#0e1416'
background = '#83d2e3'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#83d2e3'
yellow = '#006876'
blue = '#83d2e3'
magenta = '#bcc5eb'
cyan = '#b1cbd1'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
