[colors.primary]
background = '#141218'
foreground = '#e7e0e8'

[colors.cursor]
text = '#e7e0e8'
cursor = '#cbc4cf'

[colors.vi_mode_cursor]
text = '#141218'
cursor = '#d1bcfd'

[colors.search.matches]
foreground = '#49454e'
background = '#f0b8c6'

[colors.search.focused_match]
foreground = '#49454e'
background = '#d1bcfd'

[colors.footer_bar]
foreground = '#49454e'
background = '#e7e0e8'

[colors.hints.start]
foreground = '#49454e'
background = '#ccc2db'

[colors.hints.end]
foreground = '#49454e'
background = '#ccc2db'

[colors.selection]
text = '#141218'
background = '#d1bcfd'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#d1bcfd'
yellow = '#66558e'
blue = '#d1bcfd'
magenta = '#f0b8c6'
cyan = '#ccc2db'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
